const swaggerAutogen = require('swagger-autogen')();

const doc = {
  info: {
    version: '1.0.0',
    title: 'Dotion API',
    description:
      'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  host: 'localhost:5555',
  basePath: '/',
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      name: 'User',
      description: '유저 데이터 관련 API',
    },
    {
      name: 'Notion',
      description: 'Notion 데이터 관련 API',
    },
  ],
  securityDefinitions: {
    apiKeyAuth: {
      type: 'apiKey',
      in: 'header', // can be "header", "query" or "cookie"
      name: 'X-API-KEY', // name of the header, query parameter or cookie
      description: 'any description...',
    },
  },
  definitions: {
    User: {
      email: 'test@gmail.com',
      name: '홍길동',
      profile_img: 'https://www.google.com',
      token: 'adnsflkadnfsklsnafdkl',
    },
    Notion: {
      id: '1d2580f8-f0a2-4a03',
      startDate: '2022-06-20',
      endDate: '2022-06-20',
      done: false,
      title: '환경변수 설정',
      description: '리액트 네이티브 환경변수 설정 방법 공부하기',
      tagName: '온라인 회의',
      tagColor: 'yellow',
    },
    Tag: {
      name: '온라인 회의',
      color: 'yellow',
    },
  },
};

const outputFile = './swagger-output.json';
const endpointsFiles = ['./src/main.js'];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require('./src/index'); // Your project's root file
});
