const swaggerAutogen = require('swagger-autogen')();

const doc = {
  info: {
    version: '1.0.0',
    title: 'Dotion API',
    description:
      'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  host: 'localhost:5555',
  basePath: '/',
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      name: 'User',
      description: 'Endpoints',
    },
  ],
  securityDefinitions: {
    apiKeyAuth: {
      type: 'apiKey',
      in: 'header', // can be "header", "query" or "cookie"
      name: 'X-API-KEY', // name of the header, query parameter or cookie
      description: 'any description...',
    },
  },
  definitions: {
    User: {
      email: 'test@gmail.com',
      name: '홍길동',
      profile_img: 'https://www.google.com',
      token: 'adnsflkadnfsklsnafdkl',
    },
  },
};

const outputFile = './swagger-output.json';
const endpointsFiles = ['./src/main.js'];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require('./src/index'); // Your project's root file
});
